### ISSUE TITLE
combination of android sharedUserId and multik leading to crashes

### ISSUE THREAD

**Issue by meedovique** [Kotlin/multik#203]
Hi, there is some weird error when using android:sharedUserId="android.uid.system" and importing multik-core + multik-kotlin
* android:sharedUserId="android.uid.system" with keys and other android or kmp libs works
* multik also works fine, while there is no android:sharedUserId defined in manifest

Exception in runtime when using .dot 
```
Caused by java.lang.IllegalStateException: Fail to find engine. Consider to add one of the following dependencies: 
 - multik-default
 - multik-kotlin
 - multik-openblas
       at org.jetbrains.kotlinx.multik.api.EngineKt.enginesProvider(Engine.kt:13)
       at org.jetbrains.kotlinx.multik.api.Engine.<clinit>(Engine.kt:68)
       at org.jetbrains.kotlinx.multik.api.Multik.getLinalg(Multik.kt:49)
       at org.jetbrains.kotlinx.multik.api.linalg._linalgKt.dotDefMMNumber(_linalg.kt:21)
       ...
```

found in both version 0.2.2 and version 0.2.3, happens with sample android project adding just uid + signingConfigs and multik

what do you think could be the cause of such an error?

**Comment by devcrocod** [comment]
Try specifying the dependency directly: `multik-kotlin-jvm`

I'm not sure what could be causing this error. There are plans to improve android support in the next release

**Comment by meedovique** [comment]
i tried add jar files:

```
  implementation(files("libs/multik-core-jvm-0.2.3.jar"))
  implementation(files("libs/multik-kotlin-jvm-0.2.3.jar"))
```
that didn't work either

**Comment by devcrocod** [comment]
you don't need to add jar locally
in this case transitive dependencies may not work

To add, use the regular mechanism:
```
  implementation("org.jetbrains.kotlinx:multik-core-jvm:0.2.3")
  implementation("org.jetbrains.kotlinx:multik-kotlin-jvm:0.2.3")
  ```
  
  For some reason, the ServiceProvider doesn't work
  as a workaround, you can call `dot` directly:
  ```kotlin
KELinAlg.dot(...)
  ```
