### ISSUE TITLE
Jacoco is failling with java.lang.VerifyError.

### ISSUE THREAD

**Issue by koodzi** [Kotlin/multik#28]
```kotlin
fun verifyfunc(): Boolean {
    var x = FloatArray(1000) { i -> i * 0.123f }
    var y = mk.ndarray(x)
    return true
}

class MyTests {
    @Test
    fun testVerifyError() {
        verifyfunc()
        Assertions.assertTrue(verifyfunc());
    }
```

I have to do a coverage report for my code, but the above test fails  when run with coverage. Tests pass when exec. normally

```
./gradlew :lib:jacocoTestReport
```

Error:
```
java.lang.VerifyError: Inconsistent stackmap frames at branch target 256
Exception Details:
  Location:
    org/jetbrains/kotlinx/multik/api/CreateNDArrayKt.linspace$default(Lorg/jetbrains/kotlinx/multik/api/Multik;DDIILjava/lang/Object;)Lorg/jetbrains/kotlinx/multik/ndarray/data/NDArray; @256: iload
  Reason:
    Type integer (current frame, locals[9]) is not assignable to double (stack map, locals[9])
  Current Frame:
    bci: @165
    flags: { }
    locals: { 'org/jetbrains/kotlinx/multik/api/Multik', double, double_2nd, double, double_2nd, integer, integer, double, double_2nd, integer, double, double_2nd, top, 'org/jetbrains/kotlinx/multik/api/Multik', integer, integer, integer, 'org/jetbrains/kotlinx/multik/api/Multik', double, double_2nd, integer }
    stack: { integer, integer }
  Stackmap Frame:
    bci: @256
    flags: { }
    locals: { 'org/jetbrains/kotlinx/multik/api/Multik', double, double_2nd, double, double_2nd, integer, integer, double, double_2nd, double, double_2nd, top, 'org/jetbrains/kotlinx/multik/api/Multik', integer, integer, integer, 'org/jetbrains/kotlinx/multik/api/Multik', double, double_2nd, integer }
    stack: { }
  Bytecode:
    0000000: b803 263a 0815 0607 7e9a 000d 1908 1104
    0000010: 2104 54a7 0015 1908 1104 2204 5410 3236
    0000020: 0519 0811 0423 0454 0336 062a 1302 b7b8
    0000030: 0010 1505 9e00 0e04 1908 1104 2404 54a7
    0000040: 000b 0319 0811 0425 0454 3607 0336 0903
    0000050: 360a 1507 9a00 2903 360b 1302 b919 0811
    0000060: 0426 0454 3a0a bb00 5d59 190a b600 5eb7
    0000070: 0061 c000 6319 0811 0427 0454 bf15 0587
    0000080: 0f67 3907 2927 6739 0a2a 3a0d 0336 0e04
    0000090: 360f 0336 1019 0d3a 1115 0f87 3912 0336
    00000a0: 1415 0e15 05a2 005b 1812 0387 979e 000e
    00000b0: 0419 0811 0428 0454 a700 0b03 1908 1104
    00000c0: 2904 5436 1503 3616 0336 1715 1599 000d
    00000d0: 1908 1104 2a04 54a7 0092 0336 1813 026e
    00000e0: 1908 1104 2b04 543a 17bb 005d 5919 17b6
    00000f0: 005e b700 61c0 0063 1908 1104 2c04 54bf
    0000100: 150e 1505 a300 0d19 0811 042d 0454 a700
    0000110: 5b18 1203 8798 9c00 0e04 1908 1104 2e04
    0000120: 54a7 000b 0319 0811 042f 0454 3615 0336
    0000130: 1603 3617 1515 9900 0d19 0811 0430 0454
    0000140: a700 2903 3618 1302 7019 0811 0431 0454
    0000150: 3a17 bb00 5d59 1917 b600 5eb7 0061 c000
    0000160: 6319 0811 0432 0454 bf15 0587 150e 8767
    0000170: 1812 6f39 1903 3618 1819 b802 768e 3615
    0000180: 1908 1104 3304 54b2 0068 3a17 1290 b800
    0000190: 203a 1803 361b 1918 3a1c 1908 1104 3404
    00001a0: 5419 1cb2 0072 b800 20b8 0026 9900 10b2
    00001b0: 0076 1908 1104 3504 54a7 00b3 191c b200
    00001c0: 79b8 0020 b800 2699 0010 b200 7c19 0811
    00001d0: 0436 0454 a700 9819 1cb2 007f b800 20b8
    00001e0: 0026 9900 10b2 0082 1908 1104 3704 54a7
    00001f0: 007d 191c b200 85b8 0020 b800 2699 0010
    0000200: b200 8819 0811 0438 0454 a700 6219 1cb2
    0000210: 008b b800 20b8 0026 9900 10b2 008e 1908
    0000220: 1104 3904 54a7 0047 191c b200 91b8 0020
    0000230: b800 2699 0010 b200 9419 0811 043a 0454
    0000240: a700 2cbb 0096 59bb 0047 59b7 004a 1298
    0000250: b600 5019 18b8 009e b600 50b6 005b b700
    0000260: 9fc0 0063 1908 1104 3b04 54bf 003a 1604
    0000270: bc0a 5903 1515 4f3a 1719 0811 043c 0454
    0000280: 1515 1916 b800 b03a 1b03 361c 0336 1d19
    0000290: 1b3a 1e03 361f 150e 8739 2019 0811 043d
    00002a0: 0454 191e b602 7a59 b602 7f36 22b6 0282
    00002b0: 3623 1522 1523 a400 0d19 0811 043e 0454
    00002c0: a701 2b19 0811 043f 0454 0019 1e15 2218
    00002d0: 2039 2403 3626 1908 1104 4004 5412 90b8
    00002e0: 0020 3a27 1908 1104 4104 5419 27b2 0072
    00002f0: b800 20b8 0026 9900 1418 248e 91b8 00fb
    0000300: 1908 1104 4204 54a7 00ae 1927 b200 79b8
    0000310: 0020 b800 2699 0014 1824 8e93 b800 fe19
    0000320: 0811 0443 0454 a700 8f19 27b2 007f b800
    0000330: 20b8 0026 9900 1318 248e b801 0119 0811
    0000340: 0444 0454 a700 7119 27b2 0085 b800 20b8
    0000350: 0026 9900 1318 248f b801 0419 0811 0445
    0000360: 0454 a700 5319 27b2 008b b800 20b8 0026
    0000370: 9900 1318 2490 b801 0719 0811 0446 0454
    0000380: a700 3519 27b2 0091 b800 20b8 0026 9900
    0000390: 1218 24b8 010a 1908 1104 4704 54a7 0018
    00003a0: bb01 0c59 1301 0eb7 010f c000 6319 0811
    00003b0: 0448 0454 bfc0 0090 c000 6c00 1908 1104
    00003c0: 4904 54b6 0192 1820 1812 6339 2015 2215
    00003d0: 23a0 000d 1908 1104 4a04 54a7 0010 8422
    00003e0: 0119 0811 044b 0454 a7fe e200 191b 3a18
    00003f0: 1908 1104 4c04 54bb 00b2 5919 18c0 00b4
    0000400: 0319 1701 1916 b200 2ac0 001a 100a 01b7
    0000410: 00b7 003a 0c15 0504 a300 0d19 0811 044d
    0000420: 0454 a700 2818 0a18 076f 390d 1908 1104
    0000430: 4e04 5419 0cc0 0111 180d b801 0ac0 006c
    0000440: b802 bf19 0811 044f 0454 190c c001 1127
    0000450: b801 0ac0 006c b802 c219 0811 0450 0454
    0000460: 190c c001 1119 0cb6 02c5 0464 29b8 010a
    0000470: c000 6cb8 02c9 190c 3a0d 0336 0e19 0811
    0000480: 0451 0454 b200 683a 0f07 126a b800 1812
    0000490: 6cb8 0020 3a10 0336 1119 103a 1219 0811
    00004a0: 0452 0454 1912 b200 72b8 0020 b800 2699
    00004b0: 0010 b200 7619 0811 0453 0454 a700 b319
    00004c0: 12b2 0079 b800 20b8 0026 9900 10b2 007c
    00004d0: 1908 1104 5404 54a7 0098 1912 b200 7fb8
    00004e0: 0020 b800 2699 0010 b200 8219 0811 0455
    00004f0: 0454 a700 7d19 12b2 0085 b800 20b8 0026
    0000500: 9900 10b2 0088 1908 1104 5604 54a7 0062
    0000510: 1912 b200 8bb8 0020 b800 2699 0010 b200
    0000520: 8e19 0811 0457 0454 a700 4719 12b2 0091
    0000530: b800 20b8 0026 9900 10b2 0094 1908 1104
    0000540: 5804 54a7 002c bb00 9659 bb00 4759 b700
    0000550: 4a12 98b6 0050 1910 b800 9eb6 0050 b600
    0000560: 5bb7 009f c000 6319 0811 0459 0454 bf00
    0000570: 3a13 1908 1104 5a04 5419 0d19 13b6 02cd
    0000580: 1908 1104 5b04 54b0                    
  Stackmap Table:
    append_frame(@22,Object[#808])
    same_frame(@40)
    same_frame(@66)
    same_locals_1_stack_item_frame(@74,Integer)
    full_frame(@125,{Object[#211],Double,Double,Integer,Integer,Integer,Object[#808],Integer,Integer},{})
    full_frame(@187,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer},{})
    same_locals_1_stack_item_frame(@195,Integer)
    append_frame(@218,Integer,Integer,Integer)
    chop_frame(@256,3)
    same_frame(@273)
    same_frame(@292)
    same_locals_1_stack_item_frame(@300,Integer)
    append_frame(@323,Integer,Integer,Integer)
    chop_frame(@361,3)
    full_frame(@444,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Top,Object[#216],Object[#214],Double,Integer,Object[#214]},{})
    same_frame(@471)
    same_frame(@498)
    same_frame(@525)
    same_frame(@552)
    same_frame(@579)
    same_locals_1_stack_item_frame(@620,Object[#101])
    full_frame(@707,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer},{})
    same_frame(@714)
    full_frame(@778,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@809,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@839,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@869,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@899,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@928,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer})
    full_frame(@949,{Object[#211],Double,Double,Integer,Integer,Double,Double,Top,Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#214],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer,Double,Integer,Object[#214]},{Object[#398],Integer,Object[#4]})
    same_frame(@990)
    chop_frame(@1003,3)
    full_frame(@1061,{Object[#211],Double,Double,Integer,Integer,Double,Double,Object[#178],Object[#211],Integer,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#398],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer},{})
    full_frame(@1098,{Object[#211],Double,Double,Integer,Integer,Double,Double,Object[#178],Top,Top,Integer,Integer,Object[#211],Double,Integer,Integer,Object[#101],Object[#212],Object[#398],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer},{})
    full_frame(@1215,{Object[#211],Double,Double,Integer,Integer,Double,Double,Object[#178],Object[#178],Integer,Object[#216],Object[#214],Integer,Object[#214],Top,Integer,Integer,Object[#101],Object[#212],Object[#398],Double,Object[#398],Integer,Integer,Object[#398],Integer,Double,Integer,Integer},{})
    same_frame(@1242)
    same_frame(@1269)
    same_frame(@1296)
    same_frame(@1323)
    same_frame(@1350)
    same_locals_1_stack_item_frame(@1391,Object[#101])

	at MyTests.testVerifyError(MyTests.kt:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
	
	```

**Comment by koodzi** [comment]
Okey, I found an ugly solution. 

Turn off verification for coverage report only. (it's already depreacted, as of Java13)

```gradle
jacocoTestReport {
    dependsOn test

    tasks.findByName('test').doFirst {
        jvmArgs = jvmArgs << "-noverify"
    }
}
```

**Comment by devcrocod** [comment]
Hi!
This is a known issue with kotlin inline functions with default parameter: https://youtrack.jetbrains.com/issue/KT-29582
