### ISSUE TITLE
Mk.linalg.solve doesn't work with slices

### ISSUE THREAD

**Issue by msh2481** [Kotlin/multik#66]
Minimal example (it works when constructing a and b directly):
```
import org.jetbrains.kotlinx.multik.api.linalg.solve
import org.jetbrains.kotlinx.multik.api.mk
import org.jetbrains.kotlinx.multik.api.ndarray
import org.jetbrains.kotlinx.multik.ndarray.data.get

fun main(args: Array<String>) {
    val t = mk.ndarray(mk[mk[1, 2]])
    val a = t[0..1, 0..1]
    val b = t[0..1, 1]
    val c = mk.linalg.solve(a, b)
    val d = c[0]
}
```
Error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.jetbrains.kotlinx.multik.ndarray.data.MemoryViewDoubleArray.get(MemoryView.kt:668)
	at org.jetbrains.kotlinx.multik.ndarray.data.MemoryViewDoubleArray.get(MemoryView.kt:659)
	at org.jetbrains.kotlinx.multik.ndarray.data.MultiArraysKt.get0(MultiArrays.kt:183)
	at MainKt.main(Main.kt:11)
```
I'm using IntelliJ IDEA and OpenJDK JDK 17 for building.

**Comment by devcrocod** [comment]
Indeed, the exception occurs.
And result is still calculated:
```kotlin
val t = mk.ndarray(mk[mk[1, 2]]) // [[1, 2]]
val a = t[0..1, 0..1] // [[1]]
val b = t[0..1, 1] // [2]
val c = mk.linalg.solve(a, b)

println(c.data.getDoubleArray().joinToString()) // 2.0
```

The exception occurs when taking an element, I suspect that the strides were calculated incorrectly
